"""payment_movements_table

Revision ID: 63f996a68592
Revises: cb10336ce1f7
Create Date: 2025-02-27 15:40:09.316862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f996a68592'
down_revision: Union[str, None] = 'cb10336ce1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('generated_link', sa.String(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_movements_id'), 'payment_movements', ['id'], unique=False)
    op.drop_index('ix_telegram_users_user_id', table_name='telegram_users')
    op.create_index(op.f('ix_telegram_users_telegram_id'), 'telegram_users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_users_telegram_id'), table_name='telegram_users')
    op.create_index('ix_telegram_users_user_id', 'telegram_users', ['telegram_id'], unique=1)
    op.drop_index(op.f('ix_payment_movements_id'), table_name='payment_movements')
    op.drop_table('payment_movements')
    # ### end Alembic commands ###
