"""added_timestaps

Revision ID: 74277a5b995a
Revises: 63f996a68592
Create Date: 2025-02-28 06:56:00.484097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74277a5b995a'
down_revision: Union[str, None] = '63f996a68592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_movements', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payment_movements', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('telegram_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('telegram_users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'updated_at')
    op.drop_column('telegram_users', 'created_at')
    op.drop_column('payment_movements', 'updated_at')
    op.drop_column('payment_movements', 'created_at')
    # ### end Alembic commands ###
