"""deleted_date_field

Revision ID: 7cc8baccfb8d
Revises: 9205985a3b36
Create Date: 2025-03-01 01:35:44.726468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc8baccfb8d'
down_revision: Union[str, None] = '9205985a3b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_movements', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_movements', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
