"""langauge added

Revision ID: 8813d8d1546e
Revises: 7cc8baccfb8d
Create Date: 2025-03-08 22:47:00.106498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8813d8d1546e'
down_revision: Union[str, None] = '7cc8baccfb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'language')
    # ### end Alembic commands ###
