"""added_payment_type

Revision ID: 9205985a3b36
Revises: 74277a5b995a
Create Date: 2025-02-28 07:05:28.991080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9205985a3b36'
down_revision: Union[str, None] = '74277a5b995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_movements', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_movements', 'payment_type')
    # ### end Alembic commands ###
