"""missing_fix

Revision ID: cb10336ce1f7
Revises: 958336adaee2
Create Date: 2025-02-20 17:46:13.709401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb10336ce1f7'
down_revision: Union[str, None] = '958336adaee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('name', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
